name: Ethereum key check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check keys
      # --dev checks against an unpinned commit. since new vars can be added at any time unpinned commits
      # are checked on a cron, not on regular flows.
      run: ./scripts/assert_declare_ethereum_vars.sh

